### ISSUE TITLE
USBTMC Project C# Coding Issues

### ISSUE THREAD

**Issue by cherylaksh** [BKPrecisionCorp/USBTMC_CSharp#1]
When we connect the BK Precision 9115 series power supply and run the project, we are able to get the USB name in the dropdown list. But when the *IDN? command is sent, eventhough the identification response is received, the power supply shows error. Also, after that, if any *RST or *CLS commands are given, we are receiving a Visa timeout exception. Also, can anyone please let me know what are the baud rates set up for this.

**Comment by ryanroth79** [comment]
Sorry for the delay. There should be no baudrate setting for USBTMC. Please send a message to support@bkprecision.com for more help.
